version: '3'
services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
        volumes:
            - ./database/:/var/lib/postgresql/data
        ports:
          - "5433:5432"

        healthcheck:
            test: ["CMD", "pg_isready -d db -U airflow"]
            interval: 5s
            retries: 5
        restart: always

    scheduler:
        build: .
        command: poetry run airflow scheduler
        restart: on-failure
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DEBUG__FAIL_FAST=true
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - PROJECT_ID=$PROJECT_ID
            - PATH_TO_SERVICE_ACCOUNT_DIRECTORY=$PATH_TO_SERVICE_ACCOUNT_DIRECTORY
            - GCP_SERVICE_ACCOUNT_KEY_PATH=$GCP_SERVICE_ACCOUNT_KEY_PATH

        volumes:
            - ./dags:/app/airflow/dags
            - ./logs:/app/airflow/logs
            - ./data:/app/airflow/data
            - ./airbyte:/app/airflow/airbyte
            - ./project_functions:/app/airflow/project_functions
            - ./dbt_project:/app/airflow/dbt_project
            - $PATH_TO_SERVICE_ACCOUNT_DIRECTORY:/app/airflow/.gcp_keys
        tty: true
        stdin_open: true

    webserver:
        build: .
        command: poetry run scripts/entrypoint.sh
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_USER=airflow
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - PROJECT_ID=$PROJECT_ID
            - LAKE_BUCKET=$LAKE_BUCKET
            - LAKE_BUCKET_2=$LAKE_BUCKET_2
            - AIRFLOW_ADMIN_EMAIL=$AIRFLOW_ADMIN_EMAIL
            - AIRLFLOW_ADMIN_USERNAME=$AIRLFLOW_ADMIN_USERNAME
            - AIRFLOW_ADMIN_PASSWORD=$AIRFLOW_ADMIN_PASSWORD
            - AIRFLOW_ADMIN_FIRST_NAME=$AIRFLOW_ADMIN_FIRST_NAME
            - AIRFLOW_ADMIN_LAST_NAME=$AIRFLOW_ADMIN_LAST_NAME
            - GCP_SERVICE_ACCOUNT_KEY=$GCP_SERVICE_ACCOUNT_KEY
            - GCP_SERVICE_ACCOUNT_KEY_PATH=$GCP_SERVICE_ACCOUNT_KEY_PATH

        volumes:
            - ./dags:/app/airflow/dags
            - ./logs:/app/airflow/logs
            - ./data:/app/airflow/data
            - ./airbyte:/app/airflow/airbyte
            - ./project_functions:/app/airflow/project_functions
            - ./dbt_project:/app/airflow/dbt_project
            - $PATH_TO_SERVICE_ACCOUNT_DIRECTORY:/app/airflow/.gcp_keys
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        tty: true
        stdin_open: true
