version: '3'
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9001:9000"  # API
      - "9002:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: $MINIO_USER_NAME
      MINIO_ROOT_PASSWORD: $MINIO_USER_PASSWORD
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - minio-clickhouse-airflow

  clickhouse-server:
    image: altinity/clickhouse-server:24.8.14.10501.altinitystable-alpine #clickhouse/clickhouse-server:23.7.4.5-alpine #altinity/clickhouse-server:24.8.14.10501.altinitystable-alpine ## for Prod-ready or clickhouse/clickhouse-server:23.7.4.5-alpine most slightweight; altinity is more stable and i can use many useful features and analytics tools | pull from https://hub.docker.com/r/altinity/clickhouse-server/tags
    container_name: clickhousedb
    ports:
      - "8123:8123"  # Default HTTP port for ClickHouse (UI), airflow connection
      - "9000:9000"  # Default TCP port for ClickHouse, used by dbt-clickhouse
    # Set ClickHouse environment variables from .env file
    environment:
      - CLICKHOUSE_DB=$CLICKHOUSE_DB
      - CLICKHOUSE_USER=$CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1  # Enable access management for users
    volumes:
      - clickhouse-altinity-data:/var/lib/clickhouse
    networks:
      - minio-clickhouse-airflow


networks:
  minio-clickhouse-airflow:
    driver: bridge
    external: true

volumes:
  minio-data:
    external: true
  clickhouse-data:
    external: true
  clickhouse-altinity-data:
    external: true
