--CTE
with weather_data as (
	select "_airbyte_raw_id" as record_id,
			"resolvedAddress" as address,
			longitude,
			latitude,
			"_airbyte_extracted_at" as extracted_date,
			jsonb_array_elements(days) as data
	from weather_of_city
),
--PostgresSQL Syntax for handling json data
expand_data as (
 select record_id,
		split_part(address,',', 2) as region,
		split_part(address, ',', 1) as department,
		longitude,
		latitude,
		extracted_date,
		(data ->> 'datetime')::date as date_time,
		(data ->> 'datetimeEpoch')::numeric as datetimeEpoch,
		(data ->> 'tempmax')::numeric as tempmax,
	    (data ->> 'tempmin')::numeric as tempmin,
	    (data ->> 'temp')::numeric as temp,
	    (data ->> 'feelslikemax')::numeric as feelslikemax,
	    (data ->> 'feelslikemin')::numeric as feelslikemin,
	    (data ->> 'feelslike')::numeric as feelslike,
	    (data ->> 'dew')::numeric as dew,
	    (data ->> 'humidity')::numeric as humidity,
	    (data ->> 'precip')::numeric as precip,
	    (data ->> 'precipprob')::numeric as precipprob,
	    (data ->> 'precipcover')::numeric as precipcover,
	    (data ->> 'preciptype')::varchar as preciptype,
	    (data ->> 'snow')::numeric as snow,
	    (data ->> 'snowdepth')::numeric as snowdepth,
	    (data ->> 'windgust')::numeric as windgust,
	    (data ->> 'windspeed')::numeric as windspeed,
	    (data ->> 'winddir'):: numeric as winddir,
	    (data ->> 'pressure')::numeric as pressure,
	    (data ->> 'cloudcover')::numeric as cloudcover,
	    (data ->> 'visibility')::numeric as visibility,
	    (data ->> 'solarradiation')::numeric as solarradiation,
	    (data ->> 'solarenergy')::numeric as solarenergy,
	    (data ->> 'uvindex')::numeric as uvindex,
	    (data ->> 'severerisk')::numeric as severerisk,
	    (data ->> 'sunrise')::varchar as sunrise,
	    (data ->> 'sunriseEpoch')::numeric as sunriseEpoch,
	    (data ->> 'sunset')::varchar as sunset,
	    (data ->> 'sunsetEpoch')::numeric as sunsetEpoch,
	    (data ->> 'moonphase')::numeric as moonphase,
	    (data ->> 'conditions')::text as conditions,
	    (data ->> 'description')::text as descriptions,
	    (data ->> 'icon')::text as icon,
	    (data ->> 'source')::varchar as source
	from weather_data
)


--CREATE staging weather table
CREATE TABLE IF NOT EXISTS staging_weather(
  record_id numeric,
  region varchar,
  department varchar,
  longitude numeric,
  latitude numeric,
  extracted_date timestamp,
  date_time date,
  datetimeEpoch numeric,
  tempmax numeric,
  tempmin numeric,
  temp numeric,
  feelslikemax numeric,
  feelslikemin numeric,
  feelslike numeric,
  dew numeric,
  humidity numeric,
  precip numeric,
  precipprob numeric,
  precipcover numeric,
  preciptype varchar,
  snow numeric,
  snowdepth numeric,
  windgust numeric,
  windspeed numeric,
  winddir numeric,
  pressure numeric,
  cloudcover numeric,
  visibility numeric,
  solarradiation numeric,
  solarenergy numeric,
  uvindex numeric,
  severerisk numeric,
  sunrise varchar,
  sunriseEpoch numeric,
  sunset varchar,
  sunsetEpoch numeric,
  moonphase numeric,
  conditions text,
  descriptions text,
  icon text,
  source varchar,
  PRIMARY KEY (department, date_time)
);

--Insert data into staging_weather table
INSERT INTO staging_weather (record_id, region, department, longitude, latitude, extracted_date, date_time, datetimeEpoch, tempmax, tempmin, temp, feelslikemax, feelslikemin, feelslike, dew, humidity, precip, precipprob, precipcover, preciptype, snow, snowdepth, windgust, windspeed, winddir, pressure, cloudcover, visibility, solarradiation, solarenergy, uvindex, severerisk, sunrise, sunriseEpoch, sunset, sunsetEpoch, moonphase, conditions, descriptions, icon, source)
SELECT record_id, region, department, longitude, latitude, extracted_date, date_time, datetimeEpoch, tempmax, tempmin, temp, feelslikemax, feelslikemin, feelslike, dew, humidity, precip, precipprob, precipcover, preciptype, snow, snowdepth, windgust, windspeed, winddir, pressure, cloudcover, visibility, solarradiation, solarenergy, uvindex, severerisk, sunrise, sunriseEpoch, sunset, sunsetEpoch, moonphase, conditions, descriptions, icon, source
FROM expand_data;
